### PR TITLE
Fix timedimension.layer.wms for date 1970-01-01 UTC

### PR DESCRIPTION
**Pull request by erick-otenyo**
1970-01-01T00:00:00.000Z is 0 in milliseconds.
A check for time = 0 returned the base layer without the time param thus
the correct request is never made.

This pull request just removed the check for time = 0

Related to : #83

### CODE REVIEW

**Comment by bielfrontera** [comment]
Hi @erick-otenyo,
thanks for your PR!

You shouldn't modify files on **dist** folder, as they are built from the source code files that are inside the **src** folder.
So, can you modify your PR and include only modifications in files from the src folder?

**Comment by erick-otenyo** [comment]
Hi @bielfrontera 

Should be fine now ?

**Comment by bielfrontera** [comment]
Yes, it's fine! I have squashed the 3 commits into a unique commit to simplify history.
I will publish the release 1.1.2 with this fix and other changes soon!
Thanks @erick-otenyo! :)

**Comment by erick-otenyo** [comment]
Great. You are welcome!

**Pull request merged**
