### PR TITLE
Feature/new player

### PR DESCRIPTION
**Pull request by ram-one**
This is a new implementation of the player. No **jqueryUI dependencies** , works on mobiles.
- Added possibility to change animation limits with new knobs ```limitSliders=true```
- Now the player emits animation related events (play, pause, loop,...), timedimension emits events related to time loading/changing. This allows to create custom control 

As this is breaking change I changed version to 1.0.0-beta.
I also updated examples pages to use the latest 0.7.7 version.

Tested on 0.7.7 and 1.0.0b

### CODE REVIEW

**Comment by ram-one** [comment]
I didn't know which kind of indent you use. Some files used tabs, some spaces. I choose the most used in you project : 4 spaces. I may have break some code formatting.

**Comment by bielfrontera** [comment]
Thanks @ram-one, I check this!
I use spaces. I might have had a problem with the editor, an some tabs have been appeared there...

**Comment by ram-one** [comment]
You will probably notice, but I added a loop button. (I forgot to disable it by default)

```javascript
L.control.timeDimension({
        backwardButton: true,
        forwardButton: true,
        playButton: true,
        loopButton: true, // display a button to enable/disable the animation loop
        displayDate: true,
        timeSlider: true, // displays date slider
        limitSliders: true, // displays range sliders to limit animation between two bounds
        limitMinimumRange: 5, // minimum steps between lower and upper limit, animation will have at least 5 steps
        speedSlider: true
});
```

**Comment by bielfrontera** [comment]
Yes, I saw the loop button. It can be useful in some scenarios.
And I've also found the problem when the list of available times is empty (now solved).

Is it possible that [this assignment](https://github.com/ram-one/Leaflet.TimeDimension/blob/eb0c2633113e8482c8d3c2495cd35c1e85b2071b/src/leaflet.timedimension.control.js#L189) to `window.timedimension` should be removed? I suppose that is there to be able to interact with the timedimension easily from console.

Can you include in this PR the changes in the README file?

**Comment by ram-one** [comment]
Indeed, that was a debug assignment. I'll remove it.

**Comment by bielfrontera** [comment]
Would you mind to add yourself as contributor at package.json? (and bower.json)

**Pull request merged**
